/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './http-sw-proxy.module';
import * as i2 from '@angular/http';
import * as i3 from './store';
import * as i4 from './http-sw-proxy.service';
export const HttpSwProxyModuleNgFactory:i0.NgModuleFactory<i1.HttpSwProxyModule> = i0.ɵcmf(i1.HttpSwProxyModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.BrowserXhr,i2.BrowserXhr,([] as any[])),i0.ɵmpd(4608,i2.ResponseOptions,
          i2.BaseResponseOptions,([] as any[])),i0.ɵmpd(5120,i2.XSRFStrategy,i2.ɵb,
          ([] as any[])),i0.ɵmpd(4608,i2.XHRBackend,i2.XHRBackend,[i2.BrowserXhr,i2.ResponseOptions,
          i2.XSRFStrategy]),i0.ɵmpd(4608,i2.RequestOptions,i2.BaseRequestOptions,([] as any[])),
          i0.ɵmpd(5120,i2.Http,i2.ɵc,[i2.XHRBackend,i2.RequestOptions]),i0.ɵmpd(4608,
              i3.Store,i3.Store,([] as any[])),i0.ɵmpd(4608,i4.HttpSwProxy,i4.HttpSwProxy,
              [i0.PLATFORM_ID,i2.Http,i3.Store,i0.ApplicationRef]),i0.ɵmpd(512,i2.HttpModule,
              i2.HttpModule,([] as any[])),i0.ɵmpd(512,i1.HttpSwProxyModule,i1.HttpSwProxyModule,
              ([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL21zb2JhbGEvRG9jdW1lbnRzL3ByaXZhdGUvd29yay9uZy1odHRwLXN3LXByb3h5L3NyYy9odHRwLXN3LXByb3h5Lm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9tc29iYWxhL0RvY3VtZW50cy9wcml2YXRlL3dvcmsvbmctaHR0cC1zdy1wcm94eS9zcmMvaHR0cC1zdy1wcm94eS5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
